#Adding the port numbers
server:
  port: 8081

#name of the application
spring:
  application:
    name: USER-SERVICE


#data base configuration
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        currentSchema : user-rating


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka



